### ISSUE TITLE
Create function to parse text

### ISSUE THREAD

**Issue by josephhalstead** [NCBI-Hackathons/DiseaseClusters#2]
E.g. remove stopwords punctuation

**Comment by hsiaoyi0504** [comment]
``` python
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

stopWords = set(stopwords.words('english'))
data = "All work and no play makes jack dull boy. All work and no play makes jack a dull boy."
words = word_tokenize(data)
wordsFiltered = []
for w in words:
    if w not in stopWords:
        wordsFiltered.append(w)
print(wordsFiltered)
```

will output 
`['All', 'work', 'play', 'makes', 'jack', 'dull', 'boy', '.', 'All', 'work', 'play', 'makes', 'jack', 'dull', 'boy', '.']`

**Comment by lwgray** [comment]
@josephhalstead Lemmatization might be useful and also maybe n-grams.  
@hsiaoyi0504 You should do a pull request, that way we might comment on the code.

**Comment by hsiaoyi0504** [comment]
@lwgray You are right, but I need to make sure which part we want to put this in.

**Comment by hsiaoyi0504** [comment]
I think query expansion is the most important part in this application.

**Comment by hsiaoyi0504** [comment]
Solve in #8.
